### PR TITLE
Fix Redmine url locally

### PR DESCRIPTION
**Pull request by GeoDoo**

### CODE REVIEW

**Comment by ricfrank** [comment]
@GeoDoo #10 is the same  PR ?

**Comment by ricfrank** [comment]
Ok is the same branch. it is not so convenient to open a new PR every commit. How do you think ?

**Comment by ricfrank** [comment]
@GeoDoo why ? maybe i don't understand. There is the `docker-compose.yml`to do this. https://github.com/ricfrank/report-from-hell/blob/master/docker-compose.yml

**Comment by GeoDoo** [comment]
@ricfrank Yes, I know this seems weird! haha

I did it because when pinging the service from my mobile localhost:8080 does not work! 

So, i needed to put my local IP address! This is not the best way to do it, but I am not pretty sure how we can use docker to pass the ENDPOINT url there... Maybe you can help me! As for the multiple commits it is because you merged the mobile PR while i was working.... and I did not notice the mobile branch got two more commits until it was too late... haha

**Pull request closed without merging**
